#!/usr/bin/env bash

# Colors
RESET="\033[0m"
BOLD="\033[1m"

KEY="\033[38;5;81m"     # cyan-blue
VALUE="\033[38;5;214m"  # orange
WARN="\033[38;5;196m"   # red

print_line() {
    local pattern="$1"
    echo "$INFO" | grep -E "$pattern" | sed -E \
        "s/^([[:space:]]*[a-zA-Z0-9\- ]+:)[[:space:]]*(.*)$/$(printf "$KEY")\1$(printf "$RESET") $(printf "$VALUE")\2$(printf "$RESET")/"
}

#BAT_PATH=$(upower -e | grep 'BAT')
#INFO=$(upower -i "$BAT_PATH")

# If no flags are passed, print everything
#if [[ $# -eq 0 ]]; then
    #echo "$INFO"
    #exit 0
#fi

while getopts ":ptevrsca" opt; do
    case $opt in
        p) print_line "percentage:" ;;
        t) print_line "time to empty:" ;;
        e) print_line "energy:" ;;
        r) print_line "energy-rate:" ;;
        v) print_line "voltage:" ;;
        c) print_line "capacity:" ;;
        s) print_line "state:" ;;
        a) echo "$INFO" ;;
        *)
            echo "Unknown flag: -$OPTARG"
            exit 1
            ;;
    esac
done